export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

// l. 294.
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

// l. 300
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
// l. 297 Order logic into Redux.
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCES';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
// l. 303. Redirect to homepage after purchase.
export const PURCHASE_INIT = 'PURCHASE_INIT'